### ISSUE TITLE
[SPOILERS] It is possible to get stuck outside the map

### ISSUE THREAD

**Issue by Zambito1** [Shirakumo/kandria#13]
In the area that I show on the map in the attached video, I pet one of the dogs in the top right. In that area, it is too short for the player to stand up. After completing the petting animation, the player teleports outside the map.

https://user-images.githubusercontent.com/7004857/226494589-f48f8e16-be4b-4fee-b835-2488f7f2ea51.mp4

It actually looks like the map might have been made taller here (?) since this happend, but with the automatic saving, it seems like there is no way for me to get back in the map.

**Comment by Shinmera** [comment]
Wow, what a corner case.

You can get back out with the `noclip` cheat or the editor.
