### ISSUE TITLE
[Linux] Compilation errors concerning lighting-pass & hdr-output-pass

### ISSUE THREAD

**Issue by Neshamon** [Shirakumo/kandria#15]
Recently bought the game as a way to see how the trial engine works in action.
After reading the README carefully many times over, I seem to be running into a compilation issue.

Here's the error from the debugger:

```lisp
While evaluating the form starting at line 46, column 0
  of #P"/home/neshamon/quicklisp/local-projects/kandria/setup.lisp":
While evaluating the form starting at line 112, column 0
  of #P"/home/neshamon/quicklisp/local-projects/kandria/install.lisp":

debugger invoked on a SB-PCL::INVALID-SUPERCLASS in thread
#<THREAD tid=3238 "main thread" RUNNING {1001468223}>:
  The class #<SB-MOP:FORWARD-REFERENCED-CLASS TRIAL:HDR-OUTPUT-PASS> was
  specified as a superclass of the class
  #<SHADER-PASS-CLASS KANDRIA::LIGHTING-PASS {100C56E5D3}>, but the metaclasses
  #<STANDARD-CLASS SB-MOP:FORWARD-REFERENCED-CLASS> and
  #<STANDARD-CLASS TRIAL:SHADER-PASS-CLASS> are incompatible.
See also:
  AMOP, Generic Function SB-MOP:VALIDATE-SUPERCLASS
```

Any ideas why this is happening?

**Comment by Shinmera** [comment]
Trial is too new and Kandria hasn't been updated yet to work with its changes.

**Comment by Neshamon** [comment]
I was able to find the version that works with the latest Kandria, looks like it's a Trial that was updated before June 18th but after the 14th? Let me know when Kandria catches up to Trial, I look forward to playing and experimenting!

**Comment by Shinmera** [comment]
I pushed some fixes to make it work with latest. There's still a few graphical glitches, most notably on the main menu and in the dialog boxes, so it's not clear yet, but I'll see about it in the coming days.
