### ISSUE TITLE
COMPILE-FILE-ERROR  while compiling "deploy"

### ISSUE THREAD

**Issue by BAWAN97** [Shirakumo/kandria#17]
When using portacle (on Windows11) to install Kindria, some erros occurred during the compiling . Hope it gets resolved, thank you！

Here's the error infos:

    COMPILE-FILE-ERROR while
    compiling #<CL-SOURCE-FILE "deploy" "deploy">
       [Condition of type UIOP/LISP-BUILD:COMPILE-FILE-ERROR]
    
    Restarts:
     0: [RETRY] Retry compiling #<CL-SOURCE-FILE "deploy" "deploy">.
     1: [ACCEPT] Continue, treating compiling #<CL-SOURCE-FILE "deploy" "deploy"> as having been successful.
     2: [RETRY] Retry ASDF operation.
     3: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
     4: [RETRY] Retry ASDF operation.
     5: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
     --more--
    
    Backtrace:
      0: (UIOP/LISP-BUILD:CHECK-LISP-COMPILE-RESULTS NIL T T "~/asdf-action::format-action/" ((#<ASDF/LISP-ACTION:COMPILE-OP > . #<ASDF/LISP-ACTION:CL-SOURCE-FILE "deploy" "deploy">)))
      1: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "deploy" "deploy">)
      2: ((LAMBDA NIL :IN ASDF/ACTION:CALL-WHILE-VISITING-ACTION))
      3: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:COMPILE-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "deploy" "deploy">) [fast-method]
      4: ((:METHOD ASDF/PLAN:PERFORM-PLAN (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1006BD7023}>) [fast-method]
      5: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
      6: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {1006BD7023}>) [fast-method]
      7: ((:METHOD ASDF/OPERATE:OPERATE (ASDF/OPERATION:OPERATION ASDF/COMPONENT:COMPONENT)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "deploy"> :PLAN-CLASS NIL :PLAN-OPTIONS NIL) [fast-method]
      8: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "deploy"> :VERBOSE NIL)
      9: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
     10: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/SYSTEM:SYSTEM "deploy"> :VERBOSE NIL) [fast-method]
     11: ((SB-PCL::EMF ASDF/OPERATE:OPERATE) #<unused argument> #<unused argument> ASDF/LISP-ACTION:LOAD-OP "deploy" :VERBOSE NIL)
     12: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
     13: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "deploy" :VERBOSE NIL) [fast-method]
     14: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<CLOSURE (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {1006B6906B}> :OVERRIDE T :KEY NIL :OVERRIDE-CACHE T :OVERRIDE-FORCING NIL)
     15: ((LAMBDA NIL :IN ASDF/OPERATE:OPERATE))
     16: (ASDF/SESSION:CALL-WITH-ASDF-SESSION #<CLOSURE (LAMBDA NIL :IN ASDF/OPERATE:OPERATE) {1006B5365B}> :OVERRIDE NIL :KEY NIL :OVERRIDE-CACHE NIL :OVERRIDE-FORCING NIL)
     17: ((:METHOD ASDF/OPERATE:OPERATE :AROUND (T T)) ASDF/LISP-ACTION:LOAD-OP "deploy" :VERBOSE NIL) [fast-method]
     18: (ASDF/OPERATE:LOAD-SYSTEM "deploy" :VERBOSE NIL)
     19: (QUICKLISP-CLIENT::CALL-WITH-MACROEXPAND-PROGRESS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT::APPLY-LOAD-STRATEGY) {1006B5342B}>)
          Locals:
            FUN = #<CLOSURE (LAMBDA () :IN QUICKLISP-CLIENT::APPLY-LOAD-STRATEGY) {1006B5342B}>
     20: (QUICKLISP-CLIENT::AUTOLOAD-SYSTEM-AND-DEPENDENCIES "deploy" :PROMPT NIL)
     21: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION (T T)) #<unused argument> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {1006AB19EB}>) [fast-method]
     22: ((:METHOD QL-IMPL-UTIL::%CALL-WITH-QUIET-COMPILATION :AROUND (QL-IMPL:SBCL T)) #<QL-IMPL:SBCL {10068BDF83}> #<CLOSURE (FLET QUICKLISP-CLIENT::QL :IN QUICKLISP-CLIENT:QUICKLOAD) {1006AB19EB}>) [fast-me..
     23: ((:METHOD QUICKLISP-CLIENT:QUICKLOAD (T)) "deploy" :PROMPT NIL :SILENT NIL :VERBOSE NIL) [fast-method]
     24: (QL-DIST::CALL-WITH-CONSISTENT-DISTS #<CLOSURE (LAMBDA NIL :IN QUICKLISP-CLIENT:QUICKLOAD) {1006AA022B}>)
     25: (SB-INT:SIMPLE-EVAL-IN-LEXENV (QUICKLISP-CLIENT:QUICKLOAD "deploy") #<NULL-LEXENV>)
     26: (EVAL-TLF (QUICKLISP-CLIENT:QUICKLOAD "deploy") 9 NIL)
     27: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (QUICKLISP-CLIENT:QUICKLOAD "deploy") 9)
     28: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) (QUICKLISP-CLIENT:QUICKLOAD "deploy") :CURRENT-INDEX 9)
     29: (SB-C::%DO-FORMS-FROM-INFO #<CLOSURE (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {100478F85B}> #<SB-C::SOURCE-INFO {100478F813}> SB-C::INPUT-ERROR-IN-LOAD..
     30: (SB-INT:LOAD-AS-SOURCE #<SB-INT:FORM-TRACKING-STREAM for "file d:\\ProgramFiles\\Portacle\\portacle\\projects\\kandria\\setup.lisp" {100478CBD3}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
     31: ((FLET SB-FASL::THUNK :IN LOAD))
     32: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<CLOSURE (FLET SB-FASL::THUNK :IN LOAD) {612DE5B}> #<SB-INT:FORM-TRACKING-STREAM for "file d:\\ProgramFiles\\Portacle\\portacle\\projects\\kandria\\setup.lisp" {1004..
     33: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<SB-INT:FORM-TRACKING-STREAM for "file d:\\ProgramFiles\\Portacle\\portacle\\projects\\kandria\\setup.lisp" {100478CBD3}> NIL)
     34: (LOAD #P"d:/ProgramFiles/Portacle/portacle/projects/kandria/setup.lisp" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
     35: (QUICKLISP-QUICKSTART:INSTALL :PATH #P"d:/ProgramFiles/Portacle/portacle/projects/kandria/" :PROXY NIL :CLIENT-URL NIL :CLIENT-VERSION NIL :DIST-URL NIL :DIST-VERSION NIL)
     36: (ORG.SHIRAKUMO.FRAF.KANDRIA.INSTALL::INSTALL-ENVIRONMENT #P"d:/ProgramFiles/Portacle/portacle/projects/kandria/")
     37: (SB-INT:SIMPLE-EVAL-IN-LEXENV (ORG.SHIRAKUMO.FRAF.KANDRIA.INSTALL::INSTALL-ENVIRONMENT) #<NULL-LEXENV>)
     38: (EVAL-TLF (ORG.SHIRAKUMO.FRAF.KANDRIA.INSTALL::INSTALL-ENVIRONMENT) 14 NIL)
     39: ((LABELS SB-FASL::EVAL-FORM :IN SB-INT:LOAD-AS-SOURCE) (ORG.SHIRAKUMO.FRAF.KANDRIA.INSTALL::INSTALL-ENVIRONMENT) 14)
     40: ((LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) (ORG.SHIRAKUMO.FRAF.KANDRIA.INSTALL::INSTALL-ENVIRONMENT) :CURRENT-INDEX 14)
     41: (SB-C::%DO-FORMS-FROM-INFO #<CLOSURE (LAMBDA (SB-KERNEL:FORM &KEY :CURRENT-INDEX &ALLOW-OTHER-KEYS) :IN SB-INT:LOAD-AS-SOURCE) {1003CBDD5B}> #<SB-C::SOURCE-INFO {1003CBDD13}> SB-C::INPUT-ERROR-IN-LOAD..
     42: (SB-INT:LOAD-AS-SOURCE #<SB-INT:FORM-TRACKING-STREAM for "file d:\\ProgramFiles\\Portacle\\portacle\\projects\\kandria\\install.lisp" {1003CAEFB3}> :VERBOSE NIL :PRINT NIL :CONTEXT "loading")
     43: ((FLET SB-FASL::THUNK :IN LOAD))
     44: (SB-FASL::CALL-WITH-LOAD-BINDINGS #<CLOSURE (FLET SB-FASL::THUNK :IN LOAD) {612EA1B}> #<SB-INT:FORM-TRACKING-STREAM for "file d:\\ProgramFiles\\Portacle\\portacle\\projects\\kandria\\install.lisp" {10..
     45: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<SB-INT:FORM-TRACKING-STREAM for "file d:\\ProgramFiles\\Portacle\\portacle\\projects\\kandria\\install.lisp" {1003CAEFB3}> NIL)
     46: (LOAD "d:/ProgramFiles/Portacle/portacle/projects/kandria/install.lisp" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
     47: (SB-INT:SIMPLE-EVAL-IN-LEXENV (LOAD "d:/ProgramFiles/Portacle/portacle/projects/kandria/install.lisp") #<NULL-LEXENV>)
     48: (EVAL (LOAD "d:/ProgramFiles/Portacle/portacle/projects/kandria/install.lisp"))
     49: (SWANK::EVAL-REGION "(load \"d:/ProgramFiles/Portacle/portacle/projects/kandria/install.lisp\") ..)
     50: ((LAMBDA NIL :IN SWANK-REPL::REPL-EVAL))
     51: (SWANK-REPL::TRACK-PACKAGE #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {1003CAAD9B}>)
     52: (SWANK::CALL-WITH-RETRY-RESTART "Retry SLIME REPL evaluation request." #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {1003CAAD3B}>)
     53: (SWANK::CALL-WITH-BUFFER-SYNTAX NIL #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::REPL-EVAL) {1003CAAD1B}>)
     54: (SWANK-REPL::REPL-EVAL "(load \"d:/ProgramFiles/Portacle/portacle/projects/kandria/install.lisp\") ..)
     55: (SB-INT:SIMPLE-EVAL-IN-LEXENV (SWANK-REPL:LISTENER-EVAL "(load \"d:/ProgramFiles/Portacle/portacle/projects/kandria/install.lisp\") ..)
     56: (EVAL (SWANK-REPL:LISTENER-EVAL "(load \"d:/ProgramFiles/Portacle/portacle/projects/kandria/install.lisp\") ..)
     57: (SWANK:EVAL-FOR-EMACS (SWANK-REPL:LISTENER-EVAL "(load \"d:/ProgramFiles/Portacle/portacle/projects/kandria/install.lisp\") ..)
     58: (SWANK::PROCESS-REQUESTS NIL)
     59: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
     60: ((LAMBDA NIL :IN SWANK::HANDLE-REQUESTS))
     61: (SWANK/SBCL::CALL-WITH-BREAK-HOOK #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :IN SWANK::HANDLE-REQUESTS) {100420012B}>)
     62: ((FLET SWANK/BACKEND:CALL-WITH-DEBUGGER-HOOK :IN "d:/ProgramFiles/Portacle/portacle/all/emacsd/elpa/slime-20191224.2328/swank/sbcl.lisp") #<FUNCTION SWANK:SWANK-DEBUGGER-HOOK> #<CLOSURE (LAMBDA NIL :I..
     63: (SWANK::CALL-WITH-BINDINGS ((*STANDARD-INPUT* . #1=#<SWANK/GRAY::SLIME-INPUT-STREAM {1004091343}>) (*STANDARD-OUTPUT* . #2=#<SWANK/GRAY::SLIME-OUTPUT-STREAM {10041B9973}>) (*TRACE-OUTPUT* . #2#) (*ERR..
     64: (SWANK::HANDLE-REQUESTS #<SWANK::MULTITHREADED-CONNECTION {10027E8373}> NIL)
     65: ((FLET SB-UNIX::BODY :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
     66: ((FLET "WITHOUT-INTERRUPTS-BODY-4" :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
     67: ((FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE))
     68: ((FLET "WITHOUT-INTERRUPTS-BODY-1" :IN SB-THREAD::CALL-WITH-MUTEX))
     69: (SB-THREAD::CALL-WITH-MUTEX #<CLOSURE (FLET SB-THREAD::WITH-MUTEX-THUNK :IN SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE) {612FBEB}> #<SB-THREAD:MUTEX "thread result lock" owner: #<SB-THREAD:THREAD "repl-thr..
     70: (SB-THREAD::NEW-LISP-THREAD-TRAMPOLINE #<SB-THREAD:THREAD "repl-thread" RUNNING {10041D8473}> NIL #<CLOSURE (LAMBDA NIL :IN SWANK-REPL::SPAWN-REPL-THREAD) {10041D83FB}> NIL)
     71: ("foreign function: #x438ADB")
     72: ("foreign function: #x404D31")

**Comment by Shinmera** [comment]
I'm afraid this doesn't tell me anything about what the actual error is. Kandria loads fine on a properly configured system.
