### ISSUE TITLE
The `Manage Mods - Discover` doesn't works.

### ISSUE THREAD

**Issue by sakurawald** [Shirakumo/kandria#18]
![Screenshot_20241108_215628](https://github.com/user-attachments/assets/058d1ae8-c7c4-4138-aca4-f1063e11ee2d)

**Comment by Shinmera** [comment]
It does on latest.

**Comment by sakurawald** [comment]
This is the new test, i just update the content from steam.

![image](https://github.com/user-attachments/assets/1e1eac9b-c192-4761-952d-fdd8d2422772)
![image](https://github.com/user-attachments/assets/88198c0b-5fe7-43e9-a890-03212c061c80)

**Comment by Shinmera** [comment]
That's still v1.1.14, which is not latest on this repository. It hasn't been released to steam yet.

**Comment by sakurawald** [comment]
> That's still v1.1.14, which is not latest on this repository. It hasn't been released to steam yet.

Okay, thank you. I am not very curious about this issue, just want to remind you.
