### ISSUE TITLE
Failed to evaluate `(ql:quickload 'kandria)`

### ISSUE THREAD

**Issue by sakurawald** [Shirakumo/kandria#19]
I am using `lem editor`, and start `lisp repl` using `slime`.
```
; changed connection (sbcl 2.4.10.roswell)
CL-USER> (ql:quickload 'kandria)
...
```

![image](https://github.com/user-attachments/assets/102edede-d9c2-4fa2-b075-d8b955961712)
![image](https://github.com/user-attachments/assets/aa0b7386-be97-453e-8909-463d66cd3bad)

**Comment by Shinmera** [comment]
Please follow the instructions in the readme.
