### ISSUE TITLE
install.lisp: improper argument passing to quicklisp-quickstart:install

### ISSUE THREAD

**Issue by tmtvl** [Shirakumo/kandria#9]
The `quicklisp-quickstart:install` function is being called through the `f` macro, where `:path` and `path` are passed through both `install-quicklisp` and `f`'s `&amp;rest` arguments.  Therefore the argument list is only destructured once, at the boundary to `f`, but not through `install-quicklisp`, resulting in the `quicklisp-quickstart:install` function being called with the argument `(:path path)` instead of the arguments `:path path`.

I'll have a PR with a potential fix ready in a moment, we can discuss the best way to fix it there.

**Comment by Shinmera** [comment]
Sorry, the fix was so quick I didn't think you'd still submit the PR!

**Comment by tmtvl** [comment]
No problem, I didn't think you'd actually be so on top of things on a Saturday evening.
